### ISSUE TITLE
Loading through Webpack

### ISSUE THREAD

**Issue by Ibrahim-Islam** [bestiejs/platform.js#110]
When loading through Webpack its seems [this](https://github.com/bestiejs/platform.js/blob/master/platform.js#L1115) is how its setting the `platform` object but throughout the app I get `platform is not defined` when trying to access like `platform.name`. How should I be accessing `platform` when loading through Webpack?

**Comment by jdalton** [comment]
That's not a Webpack thing. That's an AMD thing. Because you're using platform in the presence of an AMD loader it assumes you're wanting to use it with the AMD loader.

We should fix this though to align with other projects which export to the global when there's an AMD loader just in case you don't want to load through it.

**Comment by Ibrahim-Islam** [comment]
@jdalton Thanks for the explanation. So, what can I do currently to workaround this?

**Comment by jdalton** [comment]
We'll need to add a bit of code to expose `platform` to the global.

**Comment by Ibrahim-Islam** [comment]
Assuming I can workaround not accessing `platform` globally, what other options do I have in consuming it? Like I tried importing `import 'platform'` in a `.ts` file and while Webpack bundle shows that its doing a require but at runtime its still the same.
