### ISSUE TITLE
Iron version not detected

### ISSUE THREAD

**Issue by freMea** [bestiejs/platform.js#136]
platform.js ersion | OS
------------------ | ----
1.3.4  | Win 10 x64 pro (french) 14393

Hi,

[Iron](http://www.srware.net/forum/viewforum.php?f=18) is a portable browser based on chromium.

At least Platform.js should detect it as Chrome in description. Its UA is peculiar because it doesn't provide its own version. Iron version = Chrome/version

`User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3100.0 Iron Safari/537.36
`

**Comment by bnjmnt4n** [comment]
Fixed in https://github.com/bestiejs/platform.js/commit/a3665f07958ec8e75f9f26ecb5682034bb1daf4b. We added support for SRWare Iron in the past, but they changed their user agent string such that the version information is encoded in the Chrome tag instead of the Iron tag as you mentioned, hence the lack of detection.
