### ISSUE TITLE
Platform product

### ISSUE THREAD

**Issue by rosygupta** [bestiejs/platform.js#151]
I'm using the library for a web application primarily used on mobile. However, the library isn't able to pickup the device name 90% of the times i.e `platform.product`. Any reasons behind it?

Chrome Version: Chrome 66.0.3359.139

**Comment by alexander255** [comment]
Looking [at the code](https://github.com/bestiejs/platform.js/blob/master/platform.js#L404) it appears that only a few well-known brands are detected. Based on the fact that this library intentionally does not come with a big database of matching patterns for different device it appears that this may not be the library you're looking for. As a matter of fact you'll likely have to build your own database for this or web-service for this.

**Comment by bnjmnt4n** [comment]
Yep, we try to keep the list of devices small: otherwise we might end up with a [huge file](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml) of regexes like other more full-featured solutions. If you do require a lot of specificity, you should try an alternative library like uap instead.
