### ISSUE TITLE
Brave and Vivaldi browser returns Chrome

### ISSUE THREAD

**Issue by BeingShaashi** [bestiejs/platform.js#193]
I don't know how this npm works.
We had used this NPM assuming this works as expected, but big issue.
For unknown browsers, it is returning "chrome" as the browser name.

**Comment by basvandenwijngaard** [comment]
Tools like this parse the browser's User Agent string to find out which browser you are using (this is the only way). You can only 'detect' what the browser is telling you.

Both Brave and Vivaldi (and some other Chromium based browsers) are not telling in their User Agent string that they are anything other than Chrome. So therefor it's impossible to detect. MS Edge does get properly detected, because it says it's Edge in it's User Agent.

Here are some examples of the current latest versions of these browsers on MacOS and their User Agents. As you can see: Brave, Vivaldi and Chrome give exactly the same User Agent.

**Brave 1.30.89  Chromium: 94.0.4606.81 (Officiële build) (x86_64)**
**UserAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36


**Vivaldi	4.3.2439.44 (Stable channel) (x86_64)**
**UserAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36


**Chrome  94.0.4606.81 (Officiële build) (x86_64)**
**UserAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36


**Microsoft Edge 94.0.992.50, Blink**
**UserAgent:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50
